### ISSUE TITLE
Failed to create a Camera Session for Camera 0

### ISSUE THREAD

**Issue by loczippo** [xulihang/react-native-barcode-overlays#3]
Hi guys,
when i click on "Scan Barcodes" button, it ask me grant a permission. i granted and it show a error. How to fix it??

https://imgur.com/a/aqiWtp4

**Comment by xulihang** [comment]
What device are you using? This is more related to vision camera. Try to post issues at its repo.

**Comment by loczippo** [comment]
SamSung S20FE
Android version: 13

bellow is video
https://drive.google.com/file/d/1YqBfgWs9Qlesc8cie9GOoXv8jDzNc1EU/view

**Comment by xulihang** [comment]
I just tested it on a Samsung Galaxy A32 device with Android 13 and it works okay. How do you install the npm packages? I use `yarn`.

**Comment by loczippo** [comment]
> I just tested it on a Samsung Galaxy A32 device with Android 13 and it works okay. How do you install the npm packages? I use `yarn`.

Thanks for the reply. I tried using `yarn` and `npm`, but I'm still encountering errors

When I remove attribute `frameProcessor={frameProcessor}` in <Camera> then camera works but it can't scan a barcode normally

I don't know what problem with frameProcessor. I will continue search

**Comment by xulihang** [comment]
The project has been updated to Vision Camera v4 so I am closing this.
